package com.echo.dictation.data.export.exporters

import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import com.echo.dictation.domain.ai.TranscriptVersion
import com.echo.dictation.domain.export.ExportOptions
import com.echo.dictation.domain.model.Transcription
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfExporter {

    fun exportToFile(
        outputFile: File,
        transcription: Transcription,
        version: TranscriptVersion?,
        options: ExportOptions
    ): File {
        val pdfDocument = PdfDocument()

        val pageWidth = 595 // Standard A4 width in points
        val pageHeight = 842 // Standard A4 height in points
        val margin = 40

        val textPaint = TextPaint().apply {
            color = Color.BLACK
            textSize = 12f
            isAntiAlias = true
            typeface = Typeface.DEFAULT
        }

        val titlePaint = TextPaint().apply {
            color = Color.rgb(30, 58, 138)
            textSize = 20f
            isAntiAlias = true
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }

        val subtitlePaint = TextPaint().apply {
            color = Color.rgb(100, 116, 139)
            textSize = 10f
            isAntiAlias = true
        }

        val headerDividerPaint = Paint().apply {
            color = Color.rgb(226, 232, 240)
            strokeWidth = 1f
        }

        val versionType = version?.versionType?.displayName ?: "Original"
        val content = version?.content ?: transcription.text
        val formattedDate = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date(transcription.timestamp))

        val contentWidth = pageWidth - (margin * 2)

        val headerBuilder = StringBuilder()
        if (options.includeDate) headerBuilder.append("Date: $formattedDate  |  ")
        if (options.includeVersionType) headerBuilder.append("Version: $versionType  |  ")
        if (options.includeModel) headerBuilder.append("Model: ${transcription.model}")

        val staticLayout = StaticLayout.Builder.obtain(content, 0, content.length, textPaint, contentWidth)
            .setAlignment(Layout.Alignment.ALIGN_NORMAL)
            .setLineSpacing(0f, 1.3f)
            .setIncludePad(false)
            .build()

        var currentY = margin + 40
        var lineIndex = 0
        val totalLines = staticLayout.lineCount
        var pageNumber = 1

        val usablePageHeight = pageHeight - margin - 50

        while (lineIndex < totalLines || pageNumber == 1) {
            val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
            val page = pdfDocument.startPage(pageInfo)
            val canvas = page.canvas

            // Page Header
            if (options.includeTitle && pageNumber == 1) {
                canvas.drawText("Echo Dictation Transcript", margin.toFloat(), (margin + 20).toFloat(), titlePaint)
                canvas.drawText(headerBuilder.toString(), margin.toFloat(), (margin + 36).toFloat(), subtitlePaint)
                canvas.drawLine(margin.toFloat(), (margin + 46).toFloat(), (pageWidth - margin).toFloat(), (margin + 46).toFloat(), headerDividerPaint)
                currentY = margin + 65
            } else {
                canvas.drawText("Echo Transcript — Page $pageNumber", margin.toFloat(), margin.toFloat(), subtitlePaint)
                canvas.drawLine(margin.toFloat(), (margin + 8).toFloat(), (pageWidth - margin).toFloat(), (margin + 8).toFloat(), headerDividerPaint)
                currentY = margin + 25
            }

            // Draw paragraph lines for this page
            while (lineIndex < totalLines && currentY < usablePageHeight) {
                val lineStart = staticLayout.getLineStart(lineIndex)
                val lineEnd = staticLayout.getLineEnd(lineIndex)
                val lineText = content.substring(lineStart, lineEnd)

                canvas.drawText(lineText, margin.toFloat(), currentY.toFloat(), textPaint)
                currentY += (staticLayout.getLineBottom(lineIndex) - staticLayout.getLineTop(lineIndex))
                lineIndex++
            }

            // Page Footer
            canvas.drawText("Generated by Echo AI • Page $pageNumber", margin.toFloat(), (pageHeight - 20).toFloat(), subtitlePaint)

            pdfDocument.finishPage(page)
            if (lineIndex >= totalLines) break
            pageNumber++
        }

        FileOutputStream(outputFile).use { out ->
            pdfDocument.writeTo(out)
        }
        pdfDocument.close()

        return outputFile
    }
}
